# Generated by Django 4.0.5 on 2022-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='app_a/project_docs/', verbose_name='Document'),
        ),
    ]
