# Generated by Django 4.0.3 on 2022-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(blank=True, max_length=10, null=True, verbose_name='Shorter Characters')),
                ('bool', models.BooleanField(default=True, verbose_name='Boolean')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('longer_char', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longer Characters')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date & Time')),
                ('integer', models.IntegerField(blank=True, null=True, verbose_name='Integer')),
                ('float_info', models.FloatField(blank=True, null=True, verbose_name='Float')),
                ('decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Decimal Number')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Long Text')),
            ],
        ),
    ]
