# Generated by Django 4.0.3 on 2022-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bool', models.BooleanField()),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('integer', models.IntegerField()),
                ('float_info', models.FloatField()),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('char', models.CharField(max_length=10)),
                ('longer_char', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
