# Generated by Django 4.0.3 on 2022-05-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='bool',
            field=models.BooleanField(default=True, verbose_name='Boolean'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='char',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Shorter Characters'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='decimal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Decimal Number'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='float_info',
            field=models.FloatField(blank=True, null=True, verbose_name='Float'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='integer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Integer'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='longer_char',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Longer Characters'),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Long Text'),
        ),
    ]
