# Generated by Django 4.0.5 on 2022-06-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplemodel',
            options={'ordering': ('-date',)},
        ),
    ]
